import { z } from 'zod'
import { conditionsSchema, historySchema, emptyHistory, restaurantSchema, actionSchema, visitSchema, feedbackSchema, genres, occasions, budgets, attributeLabels } from '../../shared/domain'
import { rankRestaurants, preferenceWeights } from '../../shared/recommendation'
import { database, requireUser, requireAdmin, restaurants, saveRestaurant } from '../services/database'
import { placeDetails, searchPlaces } from '../services/places'
export default defineEventHandler(async event=>{
 setHeader(event,'Cache-Control','no-store');const path=getRouterParam(event,'path')||'';const method=event.method
 try{
 if(path==='options'&&method==='GET')return {genres,occasions,budgets,partySizes:[1,2,4,5],attributes:attributeLabels,areas:['梅田','難波','天満','福島','中崎町','心斎橋','鶴橋','本町','天王寺','北浜'],demo:!database(event)}
 if(path==='recommendations'&&method==='POST'){
 const body=z.object({conditions:conditionsSchema.optional(),sessionId:z.string().uuid().optional(),excluded:z.array(z.string().uuid()).max(2000).default([]),history:historySchema.optional(),cursor:z.string().nullable().optional(),limit:z.number().int().min(1).max(20).default(20)}).passthrough().parse(await readBody(event));const conditions=conditionsSchema.parse(body.conditions||body);if(conditions.budgetMin!==null&&conditions.budgetMax!==null&&conditions.budgetMin>conditions.budgetMax)throw createError({statusCode:400,statusMessage:'予算の範囲を確認してください'});const all=await restaurants(event);let history=body.history||emptyHistory();const db=database(event);const quality:Record<string,{count:number;mean:number}>={};if(db){if(getHeader(event,'authorization')){const auth=await requireUser(event);const {data}=await auth.db.rpc('read_history');history=historySchema.parse(data||emptyHistory())}const {data}=await db.rpc('restaurant_quality');for(const q of data||[])quality[q.restaurant_id]={count:Number(q.answer_count),mean:Number(q.mean)}}
 const ranked=rankRestaurants(all,conditions,history,body.excluded,quality);let offset=0;if(body.cursor){try{const decoded=JSON.parse(Buffer.from(body.cursor,'base64url').toString());offset=z.number().int().min(0).max(100000).parse(decoded.offset)}catch{throw createError({statusCode:400,statusMessage:'読み込み位置が無効です'})}}const items=ranked.slice(offset,offset+body.limit);return {sessionId:body.sessionId||crypto.randomUUID(),items:items.map(r=>({...r,restaurantId:r.id})),nextCursor:offset+body.limit<ranked.length?Buffer.from(JSON.stringify({offset:offset+body.limit})).toString('base64url'):null}
 }
 if(path.startsWith('restaurants/')&&method==='GET'){const slug=path.slice(12);const r=(await restaurants(event)).find(r=>r.slug===slug);if(!r)throw createError({statusCode:404,statusMessage:'店舗が見つかりません'});const google=await placeDetails(event,r.placeId);return {...r,google,googleUnavailable:!!r.placeId&&!google}}
 if(path==='catalog'&&method==='GET')return restaurants(event)
 if(path==='history'&&method==='GET'){const {db}=await requireUser(event);const {data,error}=await db.rpc('read_history');if(error)throw error;return historySchema.parse(data||emptyHistory())}
 if(path==='history'&&method==='PUT'){const {db}=await requireUser(event);const history=historySchema.parse(await readBody(event));const all=await restaurants(event);const weights=preferenceWeights(history,all);const {error}=await db.rpc('write_history',{payload:history,weights});if(error)throw error;return {ok:true}}
 if(path==='account'&&method==='DELETE'){const {user}=await requireUser(event);const config=useRuntimeConfig(event);if(!config.supabaseSecretKey)throw createError({statusCode:503,statusMessage:'退会の設定が未完了です。運営にお問い合わせください'});const {createClient}=await import('@supabase/supabase-js');const admin=createClient(config.public.supabaseUrl,config.supabaseSecretKey,{auth:{persistSession:false}});const {error}=await admin.auth.admin.deleteUser(user.id);if(error)throw error;return {ok:true}}
 if(['favorites','visits','feedback','actions/swipe'].includes(path)||path.startsWith('favorites/')){const {db}=await requireUser(event);const {data,error}=await db.rpc('read_history');if(error)throw error;const h=historySchema.parse(data||emptyHistory());if(method==='GET'){if(path==='favorites')return (await restaurants(event)).filter(r=>h.favorites.includes(r.id));if(path==='visits')return h.visits}const body=method==='DELETE'?{}:await readBody(event);if(path==='favorites'&&method==='POST'){const id=z.string().uuid().parse(body.restaurantId);h.favorites=[...new Set([...h.favorites,id])]}else if(path.startsWith('favorites/')&&method==='DELETE'){h.favorites=h.favorites.filter(id=>id!==z.string().uuid().parse(path.slice(10)))}else if(path==='visits'&&method==='POST'){const v=visitSchema.parse({id:crypto.randomUUID(),createdAt:new Date().toISOString(),...body});if(!h.visits.some(x=>x.id===v.id))h.visits.push(v);await persist();return v}else if(path==='feedback'&&method==='POST'){const f=feedbackSchema.parse(body);if(!h.visits.some(v=>v.id===f.visitId))throw createError({statusCode:404,statusMessage:'訪問が見つかりません'});h.feedback=h.feedback.filter(x=>x.visitId!==f.visitId);h.feedback.push(f)}else if(path==='actions/swipe'&&method==='POST'){const a=actionSchema.parse({id:crypto.randomUUID(),createdAt:new Date().toISOString(),...body});if(!h.actions.some(x=>x.id===a.id)){if(a.action==='undo'){const last=[...h.actions].reverse().find(x=>x.sessionId===a.sessionId&&!x.undone&&['like','skip'].includes(x.action));if(!last||last.restaurantId!==a.restaurantId)throw createError({statusCode:409,statusMessage:'直前の操作だけ戻せます'});last.undone=true;if(last.action==='like'&&!last.wasFavorite)h.favorites=h.favorites.filter(id=>id!==last.restaurantId)}else {a.wasFavorite=h.favorites.includes(a.restaurantId);if(a.action==='like')h.favorites=[...new Set([...h.favorites,a.restaurantId])]}h.actions.push(a)}}else throw createError({statusCode:405,statusMessage:'許可されていない操作です'});await persist();return {ok:true};async function persist(){const {error}=await db.rpc('write_history',{payload:h,weights:preferenceWeights(h,await restaurants(event))});if(error)throw error}}
 if(path.startsWith('admin/')){
 const {db}=await requireAdmin(event)
 if(path==='admin/restaurants'&&method==='GET')return restaurants(event,true)
 if(path==='admin/summary'&&method==='GET'){const {data,error}=await db.rpc('restaurant_quality');if(error)throw error;return data}
 if(path==='admin/places/search'&&method==='POST'){const body=z.object({query:z.string().min(2).max(150)}).parse(await readBody(event));return searchPlaces(event,body.query)}
 if(path==='admin/restaurants'&&method==='POST')return saveRestaurant(event,restaurantSchema.parse({...await readBody(event),id:crypto.randomUUID()}))
 const match=path.match(/^admin\/restaurants\/([^/]+)(?:\/(images|publish))?$/)
 if(match){const id=z.string().uuid().parse(match[1]);const current=(await restaurants(event,true)).find(r=>r.id===id);if(!current)throw createError({statusCode:404,statusMessage:'店舗が見つかりません'});if(method==='GET')return current;if(method==='PATCH'&&!match[2])return saveRestaurant(event,restaurantSchema.parse({...current,...await readBody(event),id}));if(method==='POST'&&match[2]==='publish'){if(!current.coverImageUrl||!current.images.some(i=>i.url===current.coverImageUrl&&i.rights))throw createError({statusCode:400,statusMessage:'使用権を記録したカバー画像を選択してください'});return saveRestaurant(event,{...current,status:'published'})}
 if(method==='POST'&&match[2]==='images'){const contentLength=Number(getHeader(event,'content-length'));if(!Number.isFinite(contentLength)||contentLength>6*1024*1024)throw createError({statusCode:413,statusMessage:'画像は5MB以下にしてください'});const parts=await readMultipartFormData(event);const file=parts?.find(p=>p.name==='file');const rights=parts?.find(p=>p.name==='rights')?.data.toString().trim();const alt=parts?.find(p=>p.name==='alt')?.data.toString().trim();if(!file||file.data.length>5*1024*1024||!rights||!alt)throw createError({statusCode:400,statusMessage:'画像・代替テキスト・使用権の記録が必要です'});const b=file.data;const valid=(file.type==='image/jpeg'&&b[0]===255&&b[1]===216)||(file.type==='image/png'&&b.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))||(file.type==='image/webp'&&b.toString('ascii',0,4)==='RIFF'&&b.toString('ascii',8,12)==='WEBP');const ext=({ 'image/jpeg':'jpg','image/png':'png','image/webp':'webp'})[file.type as string];if(!valid||!ext||!new RegExp(`\\.(jpe?g|png|webp)$`,'i').test(file.filename||''))throw createError({statusCode:400,statusMessage:'JPEG・PNG・WebP画像を選んでください'});const key=`${id}/${crypto.randomUUID()}.${ext}`;const {error}=await db.storage.from('restaurant-images').upload(key,file.data,{contentType:file.type});if(error)throw error;const url=db.storage.from('restaurant-images').getPublicUrl(key).data.publicUrl;return saveRestaurant(event,{...current,images:[...current.images,{url,alt,rights,credit:parts?.find(p=>p.name==='credit')?.data.toString()||'',type:'food'}]})}
 }
 }
 throw createError({statusCode:404,statusMessage:'APIが見つかりません'})
 }catch(error:any){if(error instanceof z.ZodError)throw createError({statusCode:400,statusMessage:'入力内容を確認してください',data:error.flatten()});if(error.statusCode)throw error;console.error('API failure',error.code||error.message);throw createError({statusCode:500,statusMessage:'処理できませんでした。時間をおいて再度お試しください'})}
})
