import { describe,it,expect } from 'vitest'
import { demoRestaurants } from '../shared/demo'
import { rankRestaurants,preferenceWeights } from '../shared/recommendation'
import { emptyHistory,conditionsSchema,feedbackSchema,mergeHistory,type Conditions } from '../shared/domain'
const base:Conditions={citySlug:'osaka',genres:[],partySize:1,occasion:'',budgetMin:null,budgetMax:null}
describe('recommendation behavior',()=>{
 it('has at least 10 Osaka samples and ranks matching genres higher',()=>{expect(demoRestaurants.length).toBeGreaterThanOrEqual(10);const ramen=rankRestaurants(demoRestaurants,{...base,genres:['ramen']},emptyHistory());const cafe=rankRestaurants(demoRestaurants,{...base,genres:['cafe']},emptyHistory());expect(ramen[0]?.genres).toContain('ramen');expect(cafe[0]?.genres).toContain('cafe')})
 it('never repeats seen, blocked, closed or out-of-city candidates',()=>{const h=emptyHistory();h.blocked=[demoRestaurants[1]!.id];const candidates=[...demoRestaurants,{...demoRestaurants[2]!,id:'closed',status:'closed' as const},{...demoRestaurants[2]!,id:'other',citySlug:'tokyo' as any}];const result=rankRestaurants(candidates,base,h,[demoRestaurants[0]!.id]);expect(result.some(r=>[demoRestaurants[0]!.id,demoRestaurants[1]!.id,'closed','other'].includes(r.id))).toBe(false)})
 it('uses soft filters and at most two understandable reasons',()=>{const result=rankRestaurants(demoRestaurants,{...base,genres:['korean'],partySize:5,budgetMax:100},emptyHistory());expect(result).toHaveLength(12);expect(result.every(r=>r.recommendationReasons.length>0&&r.recommendationReasons.length<=2)).toBe(true)})
 it('changes ranking after positive feedback and does not double count edits',()=>{const h=emptyHistory();const f={visitId:crypto.randomUUID(),satisfaction:5,revisitIntention:'yes' as const,actualPartyType:'solo' as const,goodTags:['quiet'],badTags:[],privateNote:'',timeSlot:'' as const,actualBudget:''};h.feedback.push(f);expect(preferenceWeights(h,demoRestaurants).quiet).toBe(3);expect(preferenceWeights(h,demoRestaurants).date_friendly).toBe(3);const before=rankRestaurants(demoRestaurants,base,emptyHistory());const after=rankRestaurants(demoRestaurants,base,h);expect(after.map(r=>r.id)).not.toEqual(before.map(r=>r.id));expect(mergeHistory(h,h).feedback).toHaveLength(1)})
 it('weakly penalizes skip, reverses undone action, lowers noisy preference',()=>{const r=demoRestaurants[2]!;const h=emptyHistory();h.actions.push({id:crypto.randomUUID(),sessionId:crypto.randomUUID(),restaurantId:r.id,action:'skip',createdAt:new Date().toISOString(),undone:false,wasFavorite:false});expect(preferenceWeights(h,demoRestaurants).lively).toBe(-.2);h.actions[0]!.undone=true;expect(preferenceWeights(h,demoRestaurants).lively).toBeUndefined();h.feedback.push({visitId:crypto.randomUUID(),satisfaction:1,revisitIntention:'no',actualPartyType:'friends',goodTags:[],badTags:['noisy'],privateNote:'',timeSlot:'',actualBudget:''});expect(preferenceWeights(h,demoRestaurants).lively).toBe(-3)})
 it('rejects incomplete conditions and invalid feedback',()=>{expect(conditionsSchema.safeParse({}).success).toBe(false);expect(feedbackSchema.safeParse({satisfaction:6}).success).toBe(false)})
 it('keeps discovery within basic budget constraints',()=>{const ranked=rankRestaurants(demoRestaurants,{...base,genres:['ramen'],budgetMax:1000},emptyHistory());expect(ranked.filter(r=>r.exploration).every(r=>r.priceMin<=1500)).toBe(true)})
})
