import { createClient, type SupabaseClient } from '@supabase/supabase-js'
import { emptyHistory, historySchema, mergeHistory, type History, type Conditions, type Restaurant, type Feedback } from '../../shared/domain'
let client:SupabaseClient|null=null
let saveChain:Promise<unknown>=Promise.resolve()
export function useApp(){
 const config=useRuntimeConfig();const history=useState<History>('history',emptyHistory);const ready=useState('ready',()=>false);const email=useState('email',()=>'');const isAdmin=useState('is-admin',()=>false);const token=useState('token',()=>'');const owner=useState('owner',()=>'guest');const notice=useState('notice',()=>'');const syncError=useState('sync-error',()=>'');const conditions=useState<Conditions>('conditions',()=>({citySlug:'osaka',genres:[],partySize:1,occasion:'',budgetMin:null,budgetMax:null}));const sessionId=useState('session-id',()=>'');const excluded=useState<string[]>('excluded',()=>[])
 const demo=!config.public.supabaseUrl||!config.public.supabaseAnonKey
 const auth=()=>{if(demo||!import.meta.client)return null;if(!client)client=createClient(config.public.supabaseUrl,config.public.supabaseAnonKey);return client}
 const headers=()=>token.value?{Authorization:`Bearer ${token.value}`} : {}
 async function api<T>(url:string,options:any={}):Promise<T>{return $fetch<T>(url,{...options,headers:{...headers(),...options.headers}}) as Promise<T>}
 function persist(){if(import.meta.client){try{localStorage.setItem(`hitokuchi:${owner.value}`,JSON.stringify(history.value));localStorage.setItem('hitokuchi:session',JSON.stringify({id:sessionId.value,conditions:conditions.value,excluded:excluded.value}))}catch{syncError.value='端末への保存に失敗しました。ストレージの空き容量を確認してください。'}}}
 function sync(){persist();if(!token.value)return;const snapshot=JSON.parse(JSON.stringify(history.value));const accessToken=token.value;saveChain=saveChain.catch(()=>{}).then(()=>$fetch('/api/history',{method:'PUT',headers:{Authorization:`Bearer ${accessToken}`},body:snapshot})).then(()=>{syncError.value=''}).catch(()=>{syncError.value='端末には保存済みです。クラウドへの保存を再試行してください。'});return saveChain}
 function local(id:string){try{return historySchema.parse(JSON.parse(localStorage.getItem(`hitokuchi:${id}`)||JSON.stringify(emptyHistory())))}catch{return emptyHistory()}}
 async function loadSession(session:any){token.value=session?.access_token||'';email.value=session?.user.email||'';isAdmin.value=session?.user.app_metadata?.role==='admin';const id=session?.user.id||'guest';if(id===owner.value)return;owner.value=id;history.value=local(id);if(session){try{const remote=await api<History>('/api/history');history.value=mergeHistory(remote,mergeHistory(history.value,local('guest')));await sync();if(!syncError.value)localStorage.removeItem('hitokuchi:guest')}catch{syncError.value='履歴を取得できませんでした。再読み込みしてください。'}}}
 async function init(){if(ready.value)return;history.value=local('guest');try{const stored=JSON.parse(localStorage.getItem('hitokuchi:session')||'null');if(stored){sessionId.value=stored.id;conditions.value=stored.conditions;excluded.value=stored.excluded||[]}}catch{};sessionId.value ||= crypto.randomUUID();ready.value=true;const c=auth();if(c){const {data}=await c.auth.getSession();await loadSession(data.session);c.auth.onAuthStateChange((_event,session)=>{setTimeout(()=>{void loadSession(session)},0)})}}
 function startSession(next:Conditions){conditions.value=next;sessionId.value=crypto.randomUUID();excluded.value=[];persist()}
 function act(r:Restaurant,action:'like'|'skip'|'detail'){history.value.actions.push({id:crypto.randomUUID(),sessionId:sessionId.value,restaurantId:r.id,action,createdAt:new Date().toISOString(),undone:false,wasFavorite:history.value.favorites.includes(r.id)});if(action==='like')history.value.favorites=[...new Set([...history.value.favorites,r.id])];if(action!=='detail')excluded.value=[...new Set([...excluded.value,r.id])];void sync()}
 function undo(){const last=[...history.value.actions].reverse().find(a=>a.sessionId===sessionId.value&&!a.undone&&['like','skip'].includes(a.action));if(!last)return null;last.undone=true;excluded.value=excluded.value.filter(id=>id!==last.restaurantId);if(last.action==='like'&&!last.wasFavorite)history.value.favorites=history.value.favorites.filter(id=>id!==last.restaurantId);void sync();return last.restaurantId}
 function favorite(r:Restaurant){if(history.value.favorites.includes(r.id)){history.value.favorites=history.value.favorites.filter(id=>id!==r.id);void sync()}else act(r,'like')}
 function visit(r:Restaurant){const today=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo'}).format(new Date());const existing=history.value.visits.find(v=>v.restaurantId===r.id&&v.visitedAt===today);if(existing)return existing.id;const v={id:crypto.randomUUID(),restaurantId:r.id,visitedAt:today,createdAt:new Date().toISOString()};history.value.visits.push(v);void sync();return v.id}
 function feedback(f:Feedback){history.value.feedback=history.value.feedback.filter(x=>x.visitId!==f.visitId);history.value.feedback.push(f);void sync()}
 async function signOut(){await saveChain;await auth()?.auth.signOut();token.value='';email.value='';isAdmin.value=false;owner.value='guest';history.value=local('guest');excluded.value=[];sessionId.value=crypto.randomUUID();persist()}
 return {history,ready,email,isAdmin,notice,syncError,conditions,sessionId,excluded,demo,auth,api,init,startSession,act,undo,favorite,visit,feedback,sync,signOut,headers}
}
