<script setup lang="ts">
import { ArrowRight, MapPin, Sparkles, Heart, SlidersHorizontal, Check } from 'lucide-vue-next'
import { genres, occasions, budgets, type Conditions } from '../../shared/domain'
const {startSession}=useApp()
const selected=ref<string[]>([]);const party=ref<number|null>(null);const occasion=ref('');const budget=ref(4);const error=ref('')
function toggle(key:string){selected.value=selected.value.includes(key)?selected.value.filter(x=>x!==key):[...selected.value,key]}
function submit(){if(!party.value){error.value='利用人数を選んでください。';document.getElementById('party')?.scrollIntoView({behavior:'smooth',block:'center'});return}const b=budgets[budget.value]!;startSession({citySlug:'osaka',genres:selected.value,partySize:party.value as Conditions['partySize'],occasion:occasion.value,budgetMin:b.min,budgetMax:b.max});navigateTo('/recommendations')}
</script>
<template>
 <section class="hero"><div class="hero-copy"><div class="eyebrow"><span class="tiny-dot"/> OSAKA FOOD DISCOVERY</div><h1>今日の「食べたい」に、<br><em>出会おう。</em></h1><p>迷う時間も、おいしい時間に。<br>あなたの気分にぴったりな大阪のお店を、一枚ずつ。</p><a href="#find" class="button primary">お店を見つける <ArrowRight :size="19"/></a><div class="hero-note"><MapPin :size="15"/> まずは、大阪から。 <span>ログインなしではじめられます</span></div></div><div class="hero-visual"><img src="/images/table.webp" alt="さまざまな料理が並んだ食卓のイメージ" fetchpriority="high"><div class="hero-image-shade"/><span class="photo-caption">GOOD FOOD. GOOD MOOD.</span><div class="hero-sticker"><span>今日の気分で</span><strong>おいしい、<br>を見つける。</strong><Sparkles :size="23"/></div><div class="image-label"><span class="tiny-dot"/> 大阪には、まだ知らないおいしさがある。</div></div></section>
 <section id="find" class="finder-section"><div class="section-heading"><div><div class="eyebrow">LET’S FIND YOUR NEXT BITE</div><h2>今、どんな気分？</h2><p>条件を選ぶだけ。あとは、直感で。</p></div><span class="step-badge"><SlidersHorizontal :size="16"/> かんたん 4 STEP</span></div>
 <form class="finder" @submit.prevent="submit"><fieldset><legend><span class="step-number">01</span>何を食べたい？ <small>複数選択OK</small></legend><div class="genre-grid"><button v-for="g in genres" :key="g.key" type="button" class="genre-chip" :class="{selected:selected.includes(g.key)}" :aria-pressed="selected.includes(g.key)" @click="toggle(g.key)"><span class="genre-emoji">{{g.icon}}</span>{{g.label}}<Check v-if="selected.includes(g.key)" :size="14" class="chip-check"/></button><button type="button" class="genre-chip any" :class="{selected:!selected.length}" :aria-pressed="!selected.length" @click="selected=[]"><span class="genre-emoji">🍽️</span>こだわらない</button></div></fieldset>
 <div class="form-divider"/><div class="conditions-grid"><fieldset id="party"><legend><span class="step-number">02</span>何人で？ <small class="required">必須</small></legend><div class="chips"><button v-for="p in [{value:1,label:'1人'},{value:2,label:'2人'},{value:4,label:'3〜4人'},{value:5,label:'5人以上'}]" :key="p.value" type="button" :class="{selected:party===p.value}" :aria-pressed="party===p.value" @click="party=p.value;error=''">{{p.label}}</button></div></fieldset><fieldset><legend><span class="step-number">03</span>どんなシーンで？ <small>任意</small></legend><div class="chips"><button v-for="o in occasions" :key="o.key" type="button" :class="{selected:occasion===o.key}" :aria-pressed="occasion===o.key" @click="occasion=occasion===o.key?'':o.key">{{o.label}}</button></div></fieldset></div>
 <fieldset class="budget-field"><legend><span class="step-number">04</span>予算はどのくらい？ <small>1人あたり</small></legend><div class="chips"><button v-for="(b,i) in budgets" :key="b.label" type="button" :class="{selected:budget===i}" :aria-pressed="budget===i" @click="budget=i">{{b.label}}</button></div></fieldset><div class="finder-bottom"><p><Sparkles :size="17"/> 使うほど、あなた好みのおすすめに。</p><button class="button primary" type="submit">おすすめを見る <ArrowRight :size="20"/></button></div><p v-if="error" role="alert" class="error">{{error}}</p></form></section>
 <section class="how-section"><div class="eyebrow">A LITTLE SWIPE, A DELICIOUS FIND</div><h2>おいしい出会いは、かんたん。</h2><div class="how-grid"><article><span class="how-icon"><SlidersHorizontal/></span><span class="how-step">01 / CHOOSE</span><h3>気分を教えて</h3><p>食べたいもの、人数、予算。<br>今日のあなたに合わせて選びます。</p></article><article><span class="how-icon"><Heart/></span><span class="how-step">02 / SWIPE</span><h3>直感で、気になる</h3><p>一枚ずつ、お店との出会い。<br>気になったお店は右にスワイプ。</p></article><article><span class="how-icon"><Sparkles/></span><span class="how-step">03 / DISCOVER</span><h3>もっと、あなた好みに</h3><p>食べたあとの感想が、<br>次のおいしい出会いにつながります。</p></article></div></section>
</template>
