<script setup lang="ts">
import { ArrowLeft, Heart, RotateCcw, X, SlidersHorizontal, Check } from 'lucide-vue-next'
import type { Recommendation } from '../../shared/domain'
const app=useApp();const items=ref<Recommendation[]>([]);const loading=ref(false);const error=ref('');const hasMore=ref(true);const handled=ref<Recommendation|null>(null);const canUndo=ref(false);const count=ref(0);const current=computed(()=>items.value[0]);const busy=ref(false)
async function fetchMore(){if(loading.value||!hasMore.value)return;loading.value=true;error.value='';try{const result=await app.api<{items:Recommendation[];nextCursor:string|null}>('/api/recommendations',{method:'POST',body:{conditions:app.conditions.value,sessionId:app.sessionId.value,excluded:[...new Set([...app.excluded.value,...items.value.map(r=>r.id)])],history:app.history.value,limit:20}});items.value.push(...result.items);hasMore.value=!!result.nextCursor}catch{error.value='おすすめを読み込めませんでした。もう一度お試しください。'}finally{loading.value=false}}
function swipe(direction:'like'|'skip'){if(!current.value||busy.value)return;busy.value=true;const r=current.value;handled.value=r;app.act(r,direction);items.value.shift();canUndo.value=true;count.value++;if(items.value.length<=5)void fetchMore();setTimeout(()=>busy.value=false,200)}
function undo(){if(!canUndo.value||!handled.value)return;const id=app.undo();if(id){items.value.unshift(handled.value);count.value=Math.max(0,count.value-1)}canUndo.value=false}
function detail(){if(!current.value)return;app.act(current.value,'detail');navigateTo(`/restaurants/${current.value.slug}`)}
function keyboard(e:KeyboardEvent){if((e.target as HTMLElement)?.closest('button,a,input,select,textarea'))return;if(e.key==='ArrowRight')swipe('like');if(e.key==='ArrowLeft')swipe('skip')}
onMounted(async()=>{await app.init();await fetchMore();window.addEventListener('keydown',keyboard)});onUnmounted(()=>window.removeEventListener('keydown',keyboard));watch(()=>items.value[1]?.coverImageUrl,url=>{if(import.meta.client&&url){new Image().src=url}})
</script>
<template><section class="page recommendation-page"><div class="page-topline"><NuxtLink to="/" class="text-link"><ArrowLeft :size="16"/>戻る</NuxtLink><NuxtLink to="/#find" class="text-link"><SlidersHorizontal :size="16"/>条件を変更</NuxtLink></div><div class="center-heading"><div class="eyebrow">PICK YOUR NEXT BITE</div><h1>今日のあなたに、この一軒。</h1><p>気になったら右へ。違う気分なら左へ。</p></div><div class="deck"><div v-if="current"><RestaurantCard :key="current.id" :restaurant="current" @swipe="swipe" @detail="detail"/><div class="swipe-actions"><button class="swipe-button skip" @click="swipe('skip')"><X/><span>今回は見送る</span></button><button class="undo-button" :disabled="!canUndo" aria-label="直前の操作を戻す" @click="undo"><RotateCcw :size="20"/></button><button class="swipe-button like" @click="swipe('like')"><Heart/><span>気になる</span></button></div><p class="deck-count">{{count}}件チェック済み · キーボードの ← → でも操作できます</p></div><div v-else-if="loading" class="empty-state" role="status"><span class="spinner"/><h2>あなたに合うお店を探しています</h2></div><div v-else-if="!error" class="empty-state"><Check :size="40"/><h2>今日の候補をチェックしました</h2><p>気になるお店を見返したり、条件を変えて<br>新しいおいしさを見つけましょう。</p><NuxtLink to="/favorites" class="button primary">気になるお店を見る</NuxtLink><button v-if="canUndo" class="button secondary" @click="undo">直前の操作を戻す</button><NuxtLink to="/#find" class="text-link">条件を選び直す</NuxtLink></div><div v-if="error" class="error" role="alert">{{error}} <button @click="fetchMore">再試行</button></div><p v-if="loading&&current" class="muted" role="status">次のお店を読み込み中…</p></div></section></template>
