import { z } from 'zod'
export const genres = [{key:'ramen',label:'ラーメン',icon:'🍜'},{key:'seafood',label:'寿司・海鮮',icon:'🍣'},{key:'yakiniku',label:'焼肉',icon:'🥩'},{key:'izakaya',label:'居酒屋',icon:'🍻'},{key:'cafe',label:'カフェ',icon:'☕'},{key:'western',label:'洋食',icon:'🍝'},{key:'chinese',label:'中華',icon:'🥟'},{key:'korean',label:'韓国料理',icon:'🌶️'}]
export const occasions = [{key:'casual_meal',label:'普段の食事'},{key:'friends',label:'友人'},{key:'date',label:'デート'},{key:'family',label:'家族'},{key:'sightseeing',label:'観光'},{key:'business',label:'仕事・会食'},{key:'drinks',label:'飲み会'}]
export const budgets = [{label:'1,000円以下',min:0,max:1000},{label:'1,000〜2,000円',min:1000,max:2000},{label:'2,000〜4,000円',min:2000,max:4000},{label:'4,000円以上',min:4000,max:null},{label:'こだわらない',min:null,max:null}]
export const attributeLabels: Record<string,string> = {quiet:'落ち着いて話せる',lively:'にぎやか',solo_friendly:'一人で入りやすい',counter_seats:'カウンター席',good_value:'コスパが良い',large_portions:'ボリューム満点',quick_service:'提供が早い',date_friendly:'デート向き',group_friendly:'グループ向き',near_station:'駅近',photogenic:'写真映え',spicy:'辛い料理',taste:'味',service:'接客'}
export const goodTags = {taste:'味',good_value:'コストパフォーマンス',atmosphere:'雰囲気',service:'接客',large_portions:'量',near_station:'アクセス',solo_friendly:'一人で入りやすい',quiet:'落ち着いて話せる',photogenic:'写真映え',quick_service:'提供が早い'}
export const badTags = {expensive:'値段が高い',crowded:'混雑している',noisy:'騒がしい',slow:'待ち時間が長い',small_portions:'量が少ない',too_much:'量が多すぎる',not_solo:'一人では入りにくい',far:'駅から遠い',taste:'期待した味と違った',service:'接客が気になった'}
export const conditionsSchema = z.object({citySlug:z.literal('osaka').default('osaka'),genres:z.array(z.string().refine(v=>genres.some(g=>g.key===v))).max(8).default([]),partySize:z.union([z.literal(1),z.literal(2),z.literal(4),z.literal(5)]),occasion:z.string().refine(v=>!v||occasions.some(o=>o.key===v)).default(''),budgetMin:z.number().int().min(0).max(100000).nullable().default(null),budgetMax:z.number().int().min(0).max(100000).nullable().default(null)})
export type Conditions = z.infer<typeof conditionsSchema>
export const restaurantSchema = z.object({id:z.string().uuid(),slug:z.string().regex(/^[a-z0-9-]+$/).max(100),citySlug:z.literal('osaka').default('osaka'),name:z.string().min(1).max(100),area:z.string().min(1).max(50),description:z.string().max(2000),recommendationText:z.string().max(300),priceMin:z.number().int().min(0),priceMax:z.number().int().min(0),editorialScore:z.number().min(0).max(5),coverImageUrl:z.string().refine(v=>v.startsWith('/images/')||/^https:\/\//.test(v),'画像URLはHTTPSが必要です'),genres:z.array(z.string()).max(8),attributes:z.record(z.number().min(0).max(1)),partySizes:z.array(z.number().int().min(1).max(5)),occasions:z.array(z.string()),status:z.enum(['draft','published','closed']),placeId:z.string().max(300).default(''),images:z.array(z.object({url:z.string(),alt:z.string(),credit:z.string(),rights:z.string(),type:z.enum(['food','interior','exterior','menu'])})).max(20).default([]),demo:z.boolean().default(false)})
export type Restaurant = z.infer<typeof restaurantSchema>
export type Recommendation = Restaurant & {score:number;recommendationReasons:string[];exploration:boolean}
export const actionSchema=z.object({id:z.string().uuid(),sessionId:z.string().uuid(),restaurantId:z.string().uuid(),action:z.enum(['like','skip','detail','undo']),createdAt:z.string().datetime(),undone:z.boolean().default(false),wasFavorite:z.boolean().default(false)})
export const visitSchema=z.object({id:z.string().uuid(),restaurantId:z.string().uuid(),visitedAt:z.string().date(),createdAt:z.string().datetime()})
export const feedbackSchema=z.object({visitId:z.string().uuid(),satisfaction:z.number().int().min(1).max(5),revisitIntention:z.enum(['yes','maybe','no']),actualPartyType:z.enum(['solo','friends','partner','family','business','other']),goodTags:z.array(z.string().refine(v=>v in goodTags)).max(10),badTags:z.array(z.string().refine(v=>v in badTags)).max(10),privateNote:z.string().max(2000).default(''),timeSlot:z.enum(['','breakfast','lunch','dinner','other']).default(''),actualBudget:z.string().max(50).default('')})
export const historySchema=z.object({favorites:z.array(z.string().uuid()).max(2000),actions:z.array(actionSchema).max(10000),visits:z.array(visitSchema).max(2000),feedback:z.array(feedbackSchema).max(2000),blocked:z.array(z.string().uuid()).max(2000).default([])})
export type History = z.infer<typeof historySchema>
export type Feedback = z.infer<typeof feedbackSchema>
export const emptyHistory=():History=>({favorites:[],actions:[],visits:[],feedback:[],blocked:[]})
export const priceLabel=(r:Pick<Restaurant,'priceMin'|'priceMax'>)=>`¥${r.priceMin.toLocaleString('ja-JP')}〜${r.priceMax.toLocaleString('ja-JP')}`
export function mergeHistory(a:History,b:History):History { const unique=<T>(items:T[],key:(v:T)=>string)=>[...new Map(items.map(v=>[key(v),v])).values()];return {favorites:[...new Set([...a.favorites,...b.favorites])],actions:unique([...a.actions,...b.actions],v=>v.id),visits:unique([...a.visits,...b.visits],v=>v.id),feedback:unique([...a.feedback,...b.feedback],v=>v.visitId),blocked:[...new Set([...a.blocked,...b.blocked])]}}
