import { createClient } from '@supabase/supabase-js'
import type { H3Event } from 'h3'
import { demoRestaurants } from '../../shared/demo'
import type { Restaurant } from '../../shared/domain'
export function database(event:H3Event) { const config=useRuntimeConfig(event); if(!config.public.supabaseUrl||!config.public.supabaseAnonKey)return null; const token=getHeader(event,'authorization');return createClient(config.public.supabaseUrl,config.public.supabaseAnonKey,{global:{headers:token?{Authorization:token}:{}},auth:{persistSession:false,autoRefreshToken:false}}) }
export async function requireUser(event:H3Event){const db=database(event);if(!db)throw createError({statusCode:503,statusMessage:'認証サービスが未設定です'});const token=getHeader(event,'authorization')?.replace(/^Bearer /,'');if(!token)throw createError({statusCode:401,statusMessage:'ログインしてください'});const {data,error}=await db.auth.getUser(token);if(error||!data.user)throw createError({statusCode:401,statusMessage:'ログインし直してください'});return {db,user:data.user}}
const rate=new Map<string,{start:number;count:number}>()
export async function requireAdmin(event:H3Event){const auth=await requireUser(event);if(auth.user.app_metadata?.role!=='admin')throw createError({statusCode:403,statusMessage:'管理者権限が必要です'});const now=Date.now();for(const [key,value] of rate)if(now-value.start>60000)rate.delete(key);const entry=rate.get(auth.user.id)||{start:now,count:0};entry.count++;rate.set(auth.user.id,entry);if(entry.count>60)throw createError({statusCode:429,statusMessage:'少し待ってから再度お試しください'});return auth}
export async function restaurants(event:H3Event,admin=false):Promise<Restaurant[]> { const db=database(event);if(!db)return demoRestaurants;let query=db.from('restaurants').select('*, areas(name), restaurant_places(external_place_id), restaurant_attributes(strength, attributes(key,category)), restaurant_images(*)');if(!admin)query=query.eq('status','published');const {data,error}=await query;if(error){console.error('restaurant query',error.code);throw createError({statusCode:503,statusMessage:'店舗情報を取得できませんでした'})}return (data||[]).map(r=>({id:r.id,slug:r.slug,citySlug:'osaka',name:r.display_name,area:r.areas?.name||'',description:r.description,recommendationText:r.recommendation_text,priceMin:r.price_min,priceMax:r.price_max,editorialScore:Number(r.editorial_score),coverImageUrl:r.cover_image_url,status:r.status,genres:r.restaurant_attributes.filter((a:any)=>a.attributes?.category==='genre').map((a:any)=>a.attributes.key),attributes:Object.fromEntries(r.restaurant_attributes.filter((a:any)=>a.attributes?.category!=='genre').map((a:any)=>[a.attributes.key,Number(a.strength)])),partySizes:r.party_sizes,occasions:r.occasions,placeId:r.restaurant_places?.[0]?.external_place_id||'',images:r.restaurant_images.map((i:any)=>({url:i.storage_path,alt:i.alt_text,credit:i.credit_text||'',rights:i.usage_rights_note||'',type:i.image_type})),demo:r.is_demo}))}
export async function saveRestaurant(event:H3Event,r:Restaurant){const {db}=await requireAdmin(event);const {error}=await db.rpc('save_restaurant',{payload:r});if(error){console.error('save restaurant',error.code);throw createError({statusCode:400,statusMessage:'店舗の保存に失敗しました。URLの重複や入力を確認してください'})}return r}
